In [10]:
import pandas as pd

jobs = pd.read_csv("../data/postings.csv")

print(jobs.shape)

jobs.info()

jobs.head()

(123849, 31)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123849 entries, 0 to 123848
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      123849 non-null  int64
 1   company_name                122130 non-null  object
 2   title                       123849 non-null  object
 3   description                 123842 non-null  object
 4   max_salary                  29793 non-null   float64
 5   pay_period                  36073 non-null   object
 6   location                    123849 non-null  object
 7   company_id                  122132 non-null  float64
 8   views                       122160 non-null  float64
 9   med_salary                  6280 non-null    float64
 10  min_salary                  29793 non-null   float64
 11  formatted_work_type         123849 non-null  object
 12  applies                     23320 non-null   float64
 13  original_listed_time        123849 non-null  float64
 14  remote_allowed              15246 non-null   float64
 15  job_posting_url             123849 non-null  object
 16  application_url             87184 non-null   object
 17  application_type            123849 non-null  object
 18  expiry                      123849 non-null  float64
 19  closed_time                 1073 non-null    float64
 20  formatted_experience_level  94440 non-null   object
 21  skills_desc                 2439 non-null    object
 22  listed_time                 123849 non-null  float64
 23  posting_domain              83881 non-null   object
 24  sponsored                   123849 non-null  int64
 25  work_type                   123849 non-null  object
 26  currency                    36073 non-null   object
 27  compensation_type           36073 non-null   object
 28  normalized_salary           36073 non-null   float64
 29  zip_code                    102977 non-null  float64
 30  fips                        96434 non-null   float64
dtypes: float64(14), int64(2), object(15)
memory usage: 29.3+ MB

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [15]:
keep_cols = [
    'title',
    'description',
    'company_name',
    'location',
    'formatted_experience_level',
    'formatted_work_type',
    'work_type'
]

jobs = jobs[keep_cols]

print(jobs.shape)
jobs.head()

(119226, 7)

,title,description,company_name,location,formatted_experience_level,formatted_work_type,work_type
0,Marketing Coordinator,Job descriptionA leading real estate firm in N...,Corcoran Sawyer Smith,"Princeton, NJ",NaN,Full-time,FULL_TIME
1,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",NaN,"Fort Collins, CO",NaN,Full-time,FULL_TIME
2,Assitant Restaurant Manager,The National Exemplar is accepting application...,The National Exemplar,"Cincinnati, OH",NaN,Full-time,FULL_TIME
3,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,"Abrams Fensterman, LLP","New Hyde Park, NY",NaN,Full-time,FULL_TIME
4,Service Technician,Looking for HVAC service tech with experience ...,NaN,"Burlington, IA",NaN,Full-time,FULL_TIME

In [16]:
jobs.isnull().sum()

title                             0
description                       0
company_name                   1711
location                          0
formatted_experience_level    29009
formatted_work_type               0
work_type                         0
dtype: int64

In [17]:
jobs = jobs.dropna(
    subset=['description']
)

In [18]:
jobs['company_name'] = jobs[
    'company_name'
].fillna(
    'Unknown Company'
)

In [19]:
jobs[
    'formatted_experience_level'
] = jobs[
    'formatted_experience_level'
].fillna(
    'Not Specified'
)

In [20]:
jobs[
    'formatted_work_type'
] = jobs[
    'formatted_work_type'
].fillna(
    'Not Specified'
)

In [21]:
print(
    "Duplicates:",
    jobs.duplicated().sum()
)

Duplicates: 0

In [22]:
jobs = jobs.drop_duplicates()

print(jobs.shape)

(119226, 7)

In [23]:
jobs[
    'description_length'
] = jobs[
    'description'
].str.len()

In [24]:
jobs[
    'description_length'
].describe()

count    119226.000000
mean       3772.937874
std        2158.247609
min           2.000000
25%        2171.000000
50%        3445.000000
75%        4998.000000
max       23201.000000
Name: description_length, dtype: float64

In [25]:
jobs = jobs[
    jobs[
        'description_length'
    ] > 100
]

In [26]:
print(jobs.shape)

(119083, 8)

In [27]:
jobs = jobs.dropna(
    subset=['title']
)

In [28]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 119083 entries, 0 to 123848
Data columns (total 8 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   title                       119083 non-null  object
 1   description                 119083 non-null  object
 2   company_name                119083 non-null  object
 3   location                    119083 non-null  object
 4   formatted_experience_level  119083 non-null  object
 5   formatted_work_type         119083 non-null  object
 6   work_type                   119083 non-null  object
 7   description_length          119083 non-null  int64
dtypes: int64(1), object(7)
memory usage: 8.2+ MB

In [29]:
print(jobs.shape)

(119083, 8)

In [31]:
jobs.to_csv(
    "clean_jobs.csv",
    index=False
)