In [1]:
import pandas as pd
import pickle

jobs = pd.read_pickle(
    "jobs.pkl"
)

with open(
    "job_embeddings.pkl",
    "rb"
) as f:
    job_embeddings = pickle.load(f)

print(jobs.shape)
print(job_embeddings.shape)

(10000, 10)
(10000, 384)

In [6]:
import os

print(os.getcwd())

d:\job_recommendation\notebooks

In [7]:
import pdfplumber

resume_text = ""

with pdfplumber.open(
    "../Data_Sceince_Resume.pdf"
) as pdf:

    for page in pdf.pages:

        text = page.extract_text()

        if text:
            resume_text += text

print(
    resume_text[:1000]
)

Chandana Das
Adm. No. 21JE1089 (cid:131)6294091002
#21je1089@iitism.ac.in (cid:239)linkedin §github
Education
IITISMDHANBAD OCT2022–May2026
BacheloroftechnologyinEngineeringPhysics Dhanbad,Jharkhand
Projects
AzureRetailDataEngineeringPipeline|AzureDataLake,PySpark,SQL,PowerBI|Github
• Builtanend-to-endAzure-inspireddataengineeringpipelineprocessing100K+e-commercetransactionsthrough
Bronze–Silver–Goldarchitecture,implementingdataprofiling,transformation,andanalytics-readydatamodeling.
• EngineeredETLworkflowsusingPython,SQL,Parquet,andPowerBItocreatecustomer,seller,product,andsales
performancedatamarts,enablingKPItrackingandbusinessintelligencereporting.
AIPoweredJobRecommendationSystem|Python,Pandas,Scikit-learn,Streamlit|Github
• DevelopedanAI-poweredjobrecommendationplatformthatautomaticallyextractsskillsfromresumesandmatches
candidateswithrelevantopportunitiesusingNLP,SentenceTransformers,andsemanticsimilaritytechniques.
• BuiltanddeployedaninteractiveStreamlitapplicationprocessingl

In [8]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

resume_embedding = model.encode(
    resume_text,
    convert_to_numpy=True
)

print(resume_embedding.shape)

c:\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

(384,)

In [9]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(
    [resume_embedding],
    job_embeddings
).flatten()

print(similarities.shape)

(10000,)

In [10]:
import numpy as np

top_indices = np.argsort(
    similarities
)[-20:][::-1]

recommended_jobs = jobs.iloc[
    top_indices
].copy()

recommended_jobs["match_score"] = (
    similarities[top_indices]
    * 100
)

recommended_jobs[
    [
        "title",
        "company_name",
        "location",
        "match_score"
    ]
]

,title,company_name,location,match_score
235,Senior Power BI Developer,Applicantz,United States,54.158340
187,Informatica Cloud Migration Lead-24-00289,"Datasoft Technologies, Inc.","Columbus, OH",52.833782
7492,Lead Data Scientist,Intellisoft Technologies,"Virginia Beach, VA",52.001495
5583,Data Scientist - Databricks,Techions,"Santa Clara, CA",51.518124
1005,Research And Development Specialist,Net2Source Inc.,"Mossville, IL",51.389851
1509,Data Engineer - Full Time,"Computer Data Concepts, Inc","Kansas City, MO",51.208961
7771,Generative AI - Data Scientist,ChabezTech LLC,"Los Angeles, CA",50.688206
252,Sr. Azure Databricks Engineer,Sunray Informatics Inc,"Summit, NJ",50.230343
656,Technical Lead,CodeMonk,United States,50.195980
1707,Data Architect,NLB Services,"Dallas, TX",50.020527
940,Data Engineer 3: 24-00989,"Akraya, Inc.","Austin, TX",49.859985
9801,Azure Synapse Data Engineer,NLB Services,United States,49.654366
6774,MS Power Apps/Dynamics Software Engineer,Honeycomb Software,"Houston, TX",49.552708
5728,Data Science Intern DIN48,Data Glacier,United States,49.425835
4254,Junior Data Analytics Engineer,ICE,"Atlanta, GA",49.280251
3126,"Software Engineer II, Data",CDW,United States,49.247845
1590,Program Analyst Power BI,LinkTMS,"Richmond, VA",48.989742
2503,Cloud Engineer (Azure),Centraprise,"San Francisco, CA",48.615257
5422,Data Analyst,AbbVie,"Mettawa, IL",48.438549
1891,Data Engineer,Koantek,United States,48.436581

In [11]:
titles = recommended_jobs["title"]

titles.tolist()

['Senior Power BI Developer',
 ' Informatica Cloud Migration Lead-24-00289',
 'Lead Data Scientist',
 'Data Scientist - Databricks',
 'Research And Development Specialist',
 'Data Engineer - Full Time',
 'Generative AI - Data Scientist',
 'Sr. Azure Databricks Engineer',
 'Technical Lead',
 'Data Architect',
 'Data Engineer 3: 24-00989',
 'Azure Synapse Data Engineer',
 'MS Power Apps/Dynamics Software Engineer',
 'Data Science Intern DIN48',
 'Junior Data Analytics Engineer',
 'Software Engineer II, Data',
 'Program Analyst Power BI',
 'Cloud Engineer (Azure)',
 'Data Analyst',
 'Data Engineer']

In [15]:
top_indices = np.argsort(similarities)[-100:][::-1]

top_jobs = jobs.iloc[top_indices]

In [16]:
top_jobs['title']

235                      Senior Power BI Developer
187      Informatica Cloud Migration Lead-24-00289
7492                           Lead Data Scientist
5583                   Data Scientist - Databricks
1005           Research And Development Specialist
                           ...
8185                                 Data Engineer
8254               Strategic Operations Supervisor
5098          Logistics and Transportation Manager
7986    Geismar Quality Lab Technician #: 24-02677
9390            Regional Sales Manager - Northwest
Name: title, Length: 100, dtype: object

In [17]:
title_embeddings = model.encode(
    jobs['title'].tolist()
)

In [27]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=50,
    random_state=42
)

jobs['cluster'] = kmeans.fit_predict(
    job_embeddings
)

In [28]:
jobs['cluster'].value_counts()

cluster
13    326
9     308
10    304
21    288
27    288
43    275
3     274
16    273
5     269
15    264
41    262
1     250
20    235
22    234
30    224
12    224
8     223
18    223
32    222
48    219
38    219
0     214
49    210
44    208
31    193
7     192
35    191
19    191
2     190
23    189
25    189
45    188
17    184
24    184
26    179
28    174
42    169
37    168
46    168
47    160
4     159
11    156
39    129
40    119
14    118
34    112
6      95
29     87
36     53
33     27
Name: count, dtype: int64

In [29]:
role_counts = (
    top_jobs['title']
    .value_counts()
    .head(10)
)

print(role_counts)

title
Data Engineer                                 4
Data Analyst                                  2
Data Architect                                2
Data Scientist - Databricks                   1
Research And Development Specialist           1
 Informatica Cloud Migration Lead-24-00289    1
Senior Power BI Developer                     1
Generative AI - Data Scientist                1
Sr. Azure Databricks Engineer                 1
Technical Lead                                1
Name: count, dtype: int64

In [30]:
jobs['cluster'] = kmeans.labels_

jobs.groupby('cluster')['title'].count().sort_values(
    ascending=False
).head(20)

cluster
13    326
9     308
10    304
21    288
27    288
43    275
3     274
16    273
5     269
15    264
41    262
1     250
20    235
22    234
12    224
30    224
18    223
8     223
32    222
48    219
Name: title, dtype: int64

In [32]:
for c in range(20):

    print("\n")
    print("="*60)

    print(
        f"Cluster {c}"
    )

    sample_titles = (
        jobs[
            jobs['cluster']==c
        ]['title']
        .head(15)
        .tolist()
    )

    for title in sample_titles:

        print(title)

============================================================
Cluster 0
Copywriter
Marketing Intern
Marketing Assistant
Digital Marketing Manager
Social Media Marketing Specialist
Senior Copywriter
Customer Service Events Representative
Brand Director
Content Writer
Director of Paid Advertising (Legal)
Digital Marketing Assistant
Senior Editor, GOAL US
Marketing Specialist
Vice President, Marketing and Communications
TV News MMJ


============================================================
Cluster 1
Field Technician, Locator
Maintenance Technician III - Multiple Shifts
Field Service Technician
Hydroblaster/ Field Technician
PROGRAM TECHNICIAN III
Facilities Engineer
Maintenance Supervisor
Test Technician I - 2nd Shift (Onsite)
Fire Alarm Designer
HVACR Service Technician
Maintenance Mechanic Specialist I
Facilities Maintenance Technician - DIA - $32.65 Per Hour
Maintenance E&I Technician
Maintenance Tech  A
Automotive Technician


============================================================
Cluster 2
Oracle Database Administrator
LOCAL to AZ / QA Automation Engineer/SDET  USC GC ONLY
Automation Tester
Technical Writer
R Developer
Senior Oracle Database Administrator
Test Engineer
Quality Assurance Engineer (323816)
Linux System Administrator
Product Engineer (Onsite-Auburn Hills, Mi)
Junior Level QA Tester Role
Functional Tester
Product Owner - Telecom
Senior Siebel Developer
Identity Engineer


============================================================
Cluster 3
Facilities Manager
Custodian
Plant Operator
Quality Assurance Compliance Specialist - 24-65597
Custodian
Safety Manager
Mechanical Maintenance Engineer
Utility Inspector I
Technical Services Manager
Field Service Supervisor
Supervisor, Coding Services
Production Supervisor
Mechanic-Maintenance of Building-New York Eye and Ear Infirmary of Mount Sinai-Full Time- Evenings, 4pm to 12am, Rotating Weekends
Operations Supervisor
Payroll Team Lead


============================================================
Cluster 4
Senior Analyst Benefits Management & Design
NSOC Project Analyst I,
Sr SAP Business Analyst (exp w/ migration from SAP ECC 6.0 to MS Dynamics 365 preferred)
Sales and Customer Service Analyst
Cash Applications Analyst
Senior Business Analyst
Business Analyst
Passport Operations Analyst Senior
IT Business Analyst
IT Audit (Consulting) Internship - Summer 2025
Business Analyst
Peoplesoft Payroll
IT Business Analyst
Desktop Support Analyst
Platform Configuration Analyst


============================================================
Cluster 5
Metrology Engineer
Manufacturing Engineer
CNC Machinist - Day Shift
Entry-Level Electrical Analytical Design Engineer
Quality Engineer
Manufacturing Engineering Manager
New Product Development Engineer
Controls Engineers - Siemens
Civil Engineer
Senior Battery Engineer
Sales Engineer
Senior Project Engineer
Electrical Engineer (Forensics)
Research And Development Engineer
Project Engineer - Heavy Civil Construction


============================================================
Cluster 6
Store Driver
Driver Manager
Transportation Dispatcher
Carrier Sales Representative
Driver
store driver
Fleet Manager
Mobile Diesel Technician
Salesperson
Service Manager
Driver CDL
Retail Parts Pro
Customer Service Associate - Logistics
Client Services Associate (42057)
Salesperson


============================================================
Cluster 7
Assistant Director of Equipment Operations
Housekeeper
Office Manager at Fast-growing Series A Startup
Recreation Assistant - Auto Skills Center
Groomer
Service Manager
Lifeguard and Pool Monitors
Lead Environmental Services Aide
Junior Groomer
Seasonal Piecework Housekeeper
Deli Manager
Business Development Manager
Life Safety Systems Sales Representative, Electronic
Sanitation Associate
Team Member


============================================================
Cluster 8
Environmental Staff Geologist/Engineer/Scientist
Senior Associate – Newly Launched Energy Transition Platform
Corporate Counsel – Energy and Finance
Mechanical Engineer
Field Service Representative - Third Class
Quality Manager
Contract Professional (Non-Federal) - REMOTE
Senior Analyst, Financial
Senior Commercial HVAC Estimator
Sr. Director, Total Rewards
Installation Project Manager I- Des Plaines
Product Manager - Water Softener/Water Filtration
Emissions Consultant
Electrical Protection, Studies or SCADA Engineer - Senior Level
Senior Traffic Engineer


============================================================
Cluster 9
Patient Care Assistant I - Multiple openings
Medical Assistant
Practice Transformation Consultant
Welcome Coordinator
Registered Nurse - Vascular Surgery Office - (32 hours per week)
Registered Nurse
Part Time Environmental Svc Tech - Mountain View
(US) Software Implementation Consultant - Level 2 - Financial
Patient Services Coordinator-LPN Home Health Full Time
HOD Office Associate Cancer Care Clinic
Respiratory Therapist
Patient & Family Concierge (Neurosurgical Unit)
Caregiver
Medical Receptionist
Patient Services Representative - Outpatient Rehab - Full Time - Days


============================================================
Cluster 10
Personal Assistant
Customer Service Representative
Sales Resourcing Specialist
Mobile Equine Sales Director
Senior Pega Developer
Customer Service Representative
Sales Consultant
Rental Linen & Uniform Sales
Outside Sales Representative
Sales Representative
Head of Product Partnership and Issuer Advocacy
Fishing Digital Marketing Intern
Residential Sales Associate
Retail Sales Associate - North Charleston, SC
Enterprise Account Executive - Pacific North West (SLED)


============================================================
Cluster 11
Injury Examiner - various locations
Legal Billing Coordinator
Insurance Defense Associate Attorney - Hybrid Schedule
Real Estate Paralegal
Property Senior/Staff Accountant
Litigation Associate
GUNSMITH – LAW ENFORCEMENT TRAINING
Legislative Affairs Specialist (Congressional Appropriations)
Social Insurance Specialist (Claims Technical Expert) (TEMP)
Associate
Senior Litigation Associate
General Liability Associate Attorney
ESIS Claims Specialist, WC
Legal Assistant
Paralegal


============================================================
Cluster 12
Senior Consultant Validation Service
Grants Writer
Laboratory Assistant
Medical Program Manager (23-381)
Intern Corporate Development & Strategy
Director of Pharmacy
Oncology Account Manager - West Region (Remote) - 24-126
Collaborating Physician
Specialist - Environmental Health and Safety
Web Strategist- Pharmaceutical
Seasonal Support Associate - Materials Management
Senior Oncology Sales Specialist, Lung - Baltimore East - Janssen Biotech, Inc
Product Manager
Research Associate - Temporary
Senior Director, Clinical Development - Hepatology


============================================================
Cluster 13
Registered Nurse (RN), Neurosurgery
REGISTERED NURSE - MARY GRAN
Registered Nurse RN
LICENSED PRACTICAL NURSE - OAK FOREST HEALTH & REHAB CENTER
Registered Nurse (RN) - PRN Days | Clear Lake North
Educator and Infection Control RN
LPN - School Nursing
Registered Nurse
Nurse Practitioner
Registered Nurse, Per Diem Pediatrics OMC
LICENSED PRACTICAL NURSE - ROXBORO HEALTHCARE & REHABILITATION CENTER
CERTIFIED NURSING ASSISTANT - MARY GRAN
Patient Care Tech, Oncology
REGISTERED NURSE SUPERVISOR (RN) - ROXBORO HEALTHCARE & REHABILITATION CENTER
Certified Nursing Assistant (CNA) $3,500 Sign-on Bonus


============================================================
Cluster 14
Landscape Architect / Recreation & Resort Designer (0-5 Years Experience)
Proposal Writer
Senior Designer, Digital OPI
Presentation Specialist
Part-Time Remote Project Data Contributor (No experience needed) – WFH - Anywhere in US
Head of Product Design
Product Graphic Designer
UI/UX Game Designer Internship
Principal Project Manager - Strategic Projects Design Manager
Creative Designer
Senior Product Designer Manager, Consumer
Freelance Graphic Designer
Director of Technology
Landscape Designer
Electrical Designer


============================================================
Cluster 15
Residential Coach (Direct Care Position)
Licensed Clinical Social Worker
Physical Therapist
Bereavement Counselor / Social Worker
Board Certified Behavior Analyst (BCBA)
Physical Therapist PT Home Health PRN
HOME CARE PHYSICAL THERAPIST PT
Licensed Therapist for Online Counseling
Behavioral Health Professional
Psychiatrist
CERTIFIED OCCUPATIONAL THERAPY ASSISTANT (COTA) - WOODHAVEN
Physical Therapist Assistant, PTA Home Health visits
Registered Behavior Technician
Physical Therapist Assistant - Float
Occupational Therapist


============================================================
Cluster 16
Test Development Project Manager
Property Manager
Account Manager
Senior Project Manager - Hybrid
Preconstruction Manager
Construction Estimator
Project Engineer
Multi Family Project Manager (115K-135K)
Project Manager ** Remote w/ 10-20% travel **
AR-CM1 Construction Mgr I
Program Manager - Remote- US East Coast
Project Manager (65534BR)
Traveling Superintendent - Big Box Retail Construction
Estimator
Project Engineer - Heavy Industrial


============================================================
Cluster 17
Environmental Lab Tech
Sr Regulatory Affairs Specialist
Radiology Tech CT Procedures/UKHC
Associate Laboratory Quality Control
Radiologic Technologist
Associate Sample Prep Technician
Test Technician
Patient Care Technician - Neuro at UPMC West Shore
Cell Engineering Internship
Mammographer - Radiology Breast Center - PRN , Days
Per Diem Pathology Grossing Technologist
Surgical Technologist II (Non-Exempt)
Full Time Medical Lab Technician/Clinical Lab Scientist (MLT/CLS) *Up to $65,000 a year*
MRI Technologist
Animal Care Technician


============================================================
Cluster 18
Medical/Surgical/Telemetry Registered Nurse
Registered Nurse (RN) - Full-Time 2nd Shift
PACU Travel RN - Job Id: JO03720931
Registered Nurse - RN - LTAC
Travel - Telemetry - Nurse Job - $1,804/wk - $2,028/wk
Nurse - RN - ICU
Registered Nurse (RN) - Part-Time 3rd Shift
Travel ER RN job in Torrance, CA - Make $1,763 to $2,035/week
TELE Travel RN - Job Id: JO03721675
Registered Nurse - Ortho Med/Surg - Part Time Days
Travel RN - ICU - Intensive Care Unit
Weekend Registered Nurse, Days
LPN - Home Health
Registered Nurse - 4605 (Day)
Nursing Educator - $3,000 Sign-On Bonus*


============================================================
Cluster 19
Security Officer II, Protective Services (Per Diem)
System Administrator
Credentialed Background Investigator Level II
System Security Architect
LRSO Acquisition Program Management Support with Security Clearance
Security Operations Center Manager
Technical Security Engineer
CIP Network Engineer
Digital Chief Compliance Officer
EMERGENCY MANAGEMENT COORDINATOR/INSTRUCTOR II
Security Engineer 2 - IT Security Ops
Sr. Lead Information Security Analyst
Full Time 2nd Shift Security Officer
Security Officer - Call off Coverage
Senior Manager Information Security

In [33]:
resume_embedding

array([-8.16603452e-02, -6.28464371e-02, -9.37961563e-02,  5.85461967e-04,
       -4.19471301e-02, -9.56152976e-02,  3.36644128e-02,  6.48571644e-03,
       -1.28980622e-01,  4.16315719e-02,  4.61790711e-02, -8.82738233e-02,
        2.15872452e-02, -3.68853323e-02, -1.60519183e-02,  8.05424675e-02,
        5.61427884e-02, -4.46128063e-02, -9.39429924e-02, -7.75346532e-02,
        7.40265250e-02,  1.42501462e-02, -4.34838943e-02, -6.61085397e-02,
        2.55880877e-02,  2.05920264e-03, -6.92962185e-02, -9.39780381e-03,
       -9.04162880e-05, -8.02150667e-02, -4.97258827e-02,  2.35732775e-02,
       -8.05698987e-03,  7.50571713e-02,  8.64200071e-02,  4.56062704e-02,
        2.37047132e-02,  1.45191234e-02, -1.70047060e-02, -2.04119962e-02,
        2.73716431e-02, -6.24442175e-02, -3.24609801e-02, -2.66344305e-02,
       -5.35509512e-02,  6.40511699e-03, -3.24600749e-02, -7.37830475e-02,
       -3.17503363e-02,  3.97878289e-02, -9.93447602e-02,  2.70264018e-02,
       -6.13878993e-03,  1.11469738e-01,  1.38148787e-02, -6.67890022e-03,
        3.05245910e-02, -2.25770473e-02, -2.88243443e-02, -2.20106952e-02,
        4.83274609e-02, -4.09240909e-02, -1.44691141e-02, -3.15929018e-02,
        1.44762387e-02, -1.90661394e-03, -7.43118450e-02,  2.53550410e-02,
        2.86699682e-02, -6.54543564e-02, -9.77762160e-04, -6.05309568e-02,
       -1.34148821e-01,  6.80737421e-02, -4.14109230e-02,  5.37812617e-03,
        6.15227856e-02,  1.14690736e-02,  9.38764960e-02, -8.68379697e-02,
       -7.05893561e-02,  2.93625277e-02,  1.70778707e-02,  5.08457460e-02,
        3.03101446e-03,  4.63807257e-03,  1.33763878e-02,  3.24932151e-02,
        4.86691482e-02, -9.32093337e-03, -7.30738102e-04,  4.19419520e-02,
        4.13055019e-03,  1.51999937e-02,  9.83766094e-03, -3.44666913e-02,
        3.74912284e-02, -4.44834940e-02, -2.19386630e-02,  4.90318425e-02,
        1.83223933e-02,  2.01851167e-02, -4.94687892e-02, -4.89154235e-02,
       -1.31429255e-01, -5.68979234e-02,  2.24494729e-02,  8.39312077e-02,
        3.77562642e-02, -1.57472696e-02, -1.62959155e-02,  2.13332046e-02,
       -2.48792004e-02, -9.31020901e-02,  3.04391002e-03,  5.74386679e-02,
       -9.45982710e-02,  2.56863832e-02, -2.16687452e-02,  1.90769769e-02,
       -1.28194678e-03,  4.99190763e-02, -3.33956368e-02, -4.31399010e-02,
       -2.26011425e-02,  7.21723586e-03, -2.91318633e-02,  1.91807588e-32,
       -5.20363525e-02, -3.10686361e-02, -2.09352542e-02, -4.51314189e-02,
        7.29154646e-02, -1.69391986e-02,  2.88488027e-02,  1.59437377e-02,
       -3.38653848e-02,  1.47852749e-02, -7.36536905e-02,  9.28215608e-02,
       -9.37074572e-02,  8.89073610e-02,  7.48992115e-02, -9.62435752e-02,
        3.81894447e-02,  2.43579280e-02,  3.02932914e-02, -1.42121753e-02,
        6.80283904e-02, -7.04289153e-02, -3.62576684e-04,  2.25725751e-02,
        1.76639669e-02, -1.45513201e-02,  4.18802500e-02,  4.80608735e-03,
        3.20744067e-02,  7.88594931e-02,  1.30005497e-02, -2.31379550e-02,
       -9.82329845e-02, -5.29761985e-02, -7.20531419e-02, -3.70725803e-02,
       -6.20551743e-02, -7.32889622e-02,  3.25226411e-02, -2.92597488e-02,
       -5.23998477e-02,  6.98346645e-02, -6.29441738e-02,  1.29226698e-02,
       -1.74978636e-02,  2.24787910e-02,  2.21115537e-02,  7.15510696e-02,
        6.38277531e-02,  4.66614738e-02, -7.86534548e-02, -1.66409952e-03,
        9.49585438e-02,  3.78683605e-03, -4.72715646e-02,  1.22404071e-02,
        3.91111337e-02, -3.07693593e-02,  1.72571381e-04,  5.07357791e-02,
       -1.34579197e-01,  2.85980385e-02, -3.53720039e-02, -1.48895942e-02,
        1.84994489e-02,  1.56523532e-03,  4.67108004e-02, -3.25489677e-02,
        4.45236750e-02, -2.46101674e-02, -7.69727901e-02, -2.35314164e-02,
        3.78186628e-02,  5.03693074e-02,  3.19667757e-02, -5.15665375e-02,
        2.23791171e-02, -2.54201759e-02, -3.84407975e-02, -4.80625704e-02,
       -8.27701688e-02,  8.57623667e-02, -4.53836657e-03, -6.71386570e-02,
       -3.51935737e-02,  1.79835446e-02,  9.07470379e-03, -4.93664667e-02,
       -4.36104499e-02, -2.85988096e-02,  1.23216920e-02,  1.68344826e-02,
        2.83715595e-02,  8.10704827e-02, -4.32781056e-02, -1.80370028e-32,
       -8.17108061e-03, -4.66486141e-02, -8.44141990e-02,  3.53542231e-02,
        7.74113834e-02, -1.53979994e-02,  2.27236710e-02, -3.25984396e-02,
        3.88922058e-02, -1.00666191e-02,  1.12159215e-02,  6.95274398e-03,
       -2.56590400e-04, -5.01508033e-03,  2.96989884e-02, -1.29774213e-02,
        7.71360612e-03,  2.52084155e-02,  2.85173096e-02,  6.08149990e-02,
        7.01448834e-03,  1.69307753e-01, -9.04740691e-02,  2.75594462e-03,
       -2.72447523e-02,  4.32048962e-02, -4.73394990e-02,  2.13227887e-02,
        4.63987179e-02, -1.69385020e-02,  6.55745761e-03, -2.02885997e-02,
       -7.83722773e-02,  1.43298367e-02, -7.71787167e-02, -4.46112230e-02,
        9.18199047e-02, -4.72621396e-02, -3.24709378e-02,  3.59518752e-02,
        1.35513082e-01,  1.31448526e-02, -3.84965651e-02,  1.56635195e-02,
       -1.50940269e-02, -9.24219936e-03, -5.80296963e-02,  7.14153377e-03,
       -4.53011086e-03,  2.62791943e-02,  5.49167395e-02,  6.43161461e-02,
        2.22447398e-03,  7.12536499e-02,  1.78969633e-02, -1.29055348e-04,
        1.17483370e-01,  7.00529246e-03, -1.38094515e-01, -3.70172299e-02,
       -1.62524991e-02,  4.34678197e-02,  1.21619046e-01,  6.39420934e-03,
        6.73683658e-02,  1.85327493e-02,  4.27029021e-02,  1.03664631e-02,
       -4.23457026e-02, -1.22926161e-01,  2.92290337e-02, -2.76457705e-02,
        4.35732342e-02, -3.94052975e-02,  6.52860990e-03, -9.08689015e-03,
       -2.68063266e-02, -3.77761647e-02, -3.11498679e-02, -9.82283521e-03,
       -5.49650118e-02,  8.71989429e-02,  6.89133182e-02,  1.90894082e-02,
        2.79048234e-02, -1.48044564e-02,  1.16845621e-02,  3.58463079e-02,
        2.08802857e-02,  1.75050274e-02, -8.64630193e-02, -5.54024205e-02,
       -2.39247847e-02,  1.18637428e-01,  5.61593892e-03, -7.92302615e-08,
       -3.00065912e-02, -5.71865914e-03, -8.13106075e-03, -2.60587927e-04,
       -2.78920308e-03,  7.61412363e-03,  7.60455849e-03,  1.21805027e-01,
       -5.79241524e-03, -8.17569718e-02,  4.76999134e-02,  2.38113273e-02,
       -6.26765788e-02,  1.87130366e-02,  6.21462353e-02, -3.10017504e-02,
        4.47883606e-02,  1.57714728e-02, -5.45865744e-02, -1.06121071e-01,
        1.45950653e-02, -1.59165133e-02,  3.11282137e-03, -1.21054938e-02,
       -4.83947657e-02,  3.15232645e-03,  2.92938482e-02,  2.24330532e-03,
        7.16453604e-03, -3.02392710e-02, -4.98721451e-02,  8.92902818e-03,
        8.97609070e-02, -5.95084913e-02,  4.54616956e-02,  1.04816899e-01,
       -5.36214700e-03, -1.37599977e-02,  2.71029752e-02,  3.64480615e-02,
       -5.08042946e-02,  2.25698929e-02, -1.27067892e-02,  1.01291453e-02,
        5.60184009e-02,  9.58840270e-03, -1.10159300e-01,  5.01148542e-03,
        5.91408201e-02,  9.10404138e-03, -6.00692779e-02, -4.71340381e-02,
        2.12500487e-02,  2.53989175e-03, -3.50847444e-03,  8.96006078e-02,
       -6.93457127e-02, -7.21484870e-02,  3.28351855e-02,  1.02350526e-01,
        1.33926004e-01, -5.69684468e-02,  1.52495746e-02, -1.92396957e-02],
      dtype=float32)

In [34]:
top_jobs

,title,description,company_name,location,formatted_experience_level,formatted_work_type,work_type,description_length,job_text,job_text_length
235,Senior Power BI Developer,"VISA SPONSORSHIP IS NOT AVAILABLE.\nOur large,...",Applicantz,United States,Mid-Senior level,Contract,CONTRACT,1927,Senior Power BI Developer VISA SPONSORSHIP IS ...,1953
187,Informatica Cloud Migration Lead-24-00289,Informatica Cloud Migration LeadOnsiteAbout th...,"Datasoft Technologies, Inc.","Columbus, OH",Mid-Senior level,Contract,CONTRACT,1800,Informatica Cloud Migration Lead-24-00289 Inf...,1843
7492,Lead Data Scientist,Company DescriptionIntellisoft Technologies is...,Intellisoft Technologies,"Virginia Beach, VA",Not Specified,Contract,CONTRACT,2300,Lead Data Scientist Company DescriptionIntelli...,2320
5583,Data Scientist - Databricks,"At Techions, we pride ourselves on being at th...",Techions,"Santa Clara, CA",Not Specified,Full-time,FULL_TIME,3348,"Data Scientist - Databricks At Techions, we pr...",3028
1005,Research And Development Specialist,Job Title: Development/Research Engineer Locat...,Net2Source Inc.,"Mossville, IL",Associate,Contract,CONTRACT,2356,Research And Development Specialist Job Title:...,2392
...,...,...,...,...,...,...,...,...,...,...
8185,Data Engineer,We are actively seeking a Financial Data Engin...,Unknown Company,New York City Metropolitan Area,Not Specified,Full-time,FULL_TIME,1569,Data Engineer We are actively seeking a Financ...,1583
8254,Strategic Operations Supervisor,\nJob Description \n\n** Please note; an activ...,"BAE Systems, Inc.","Nashua, NH",Mid-Senior level,Full-time,FULL_TIME,5161,Strategic Operations Supervisor \nJob Descript...,3032
5098,Logistics and Transportation Manager,REQ ID – 32309173ROLE – Logistics and Transpor...,WalkWater Technologies,"Austin, TX",Mid-Senior level,Contract,CONTRACT,1033,Logistics and Transportation Manager REQ ID – ...,1070
7986,Geismar Quality Lab Technician #: 24-02677,Job Title: Geismar Quality Lab Technician\n\nL...,HireTalent - Diversity Staffing & Recruiting Firm,"Geismar, LA",Mid-Senior level,Contract,CONTRACT,4317,Geismar Quality Lab Technician #: 24-02677 Job...,3043
9390,Regional Sales Manager - Northwest,Power the Future with us!\nSolarEdge (NASDAQ: ...,SolarEdge Technologies,"Portland, Oregon Metropolitan Area",Mid-Senior level,Full-time,FULL_TIME,5208,Regional Sales Manager - Northwest Power the F...,3035

In [36]:
print(jobs.columns)

Index(['title', 'description', 'company_name', 'location',
       'formatted_experience_level', 'formatted_work_type', 'work_type',
       'description_length', 'job_text', 'job_text_length', 'cluster'],
      dtype='object')

In [37]:
print(top_jobs.columns)

Index(['title', 'description', 'company_name', 'location',
       'formatted_experience_level', 'formatted_work_type', 'work_type',
       'description_length', 'job_text', 'job_text_length'],
      dtype='object')

In [39]:
jobs['cluster'] = kmeans.fit_predict(job_embeddings)

In [40]:
jobs.to_pickle("clustered_jobs.pkl")

In [41]:
jobs = pd.read_pickle("clustered_jobs.pkl")

In [42]:
print(jobs.columns)

Index(['title', 'description', 'company_name', 'location',
       'formatted_experience_level', 'formatted_work_type', 'work_type',
       'description_length', 'job_text', 'job_text_length', 'cluster'],
      dtype='object')

In [43]:
top_indices = np.argsort(
    similarities
)[-100:][::-1]

top_jobs = jobs.iloc[top_indices].copy()

In [44]:
top_jobs['cluster'].value_counts()

cluster
26    42
2     15
20    10
30     7
8      4
46     4
44     3
5      3
27     3
3      2
28     2
24     1
4      1
10     1
25     1
23     1
Name: count, dtype: int64

In [45]:
top_jobs[
    top_jobs['cluster'] == 26
][['title']].head(30)

                                             title
235                      Senior Power BI Developer
187      Informatica Cloud Migration Lead-24-00289
7492                           Lead Data Scientist
5583                   Data Scientist - Databricks
1509                     Data Engineer - Full Time
7771                Generative AI - Data Scientist
252                  Sr. Azure Databricks Engineer
656                                 Technical Lead
1707                                Data Architect
940                      Data Engineer 3: 24-00989
9801                   Azure Synapse Data Engineer
6774      MS Power Apps/Dynamics Software Engineer
5728                     Data Science Intern DIN48
4254                Junior Data Analytics Engineer
3126                    Software Engineer II, Data
1590                      Program Analyst Power BI
5422                                  Data Analyst
1891                                 Data Engineer
8898                 Datawarehouse / ETL Developer
7944      Senior Data Modeler  (14+ years minimum)
2843                       IT Director - Pre Trade
4146                                 Data Engineer
8563                               Data Engineer I
4668                  Databricks Platform Engineer
5589                     Databricks Data Architect
3862         Senior Data Analyst - Cloud Solutions
9909             Software Engineer, Data Streaming
2789                     Data Management Developer
103   Sales Executive - Manufacturing Intelligence
343                             Lead Data Engineer

In [46]:
top_jobs[
    top_jobs['cluster'] == 2
][['title']].head(30)

                                                  title
9129                     Data Systems Engineer - Onsite
4654                                 SAP System Analyst
6808  Senior Quality Assurance Analyst-ProdDev Bay Area
7988          Oracle Fusion Cloud  (Finance) Developer
8219      Senior Technical Lead - Investment Management
2881                        Production Support Engineer
5136  Summer IT Intern - Identity & Access Mgmt Engi...
3637                          Sr. Application Developer
2514                SAP FICA with Utilities- Functional
1369                        SDET/QA Automation Engineer
2020                          SAP FICO – AMS Consultant
1494                           OFSAA Programmer/Analyst
8262  Oracle CDM Cloud Technical Specialist - New Yo...
6633                                  Technical Analyst
4270                              Oracle EBS Functional

In [47]:
top_jobs[
    top_jobs['cluster'] == 20
][['title']].head(30)

                                                  title
2503                             Cloud Engineer (Azure)
7859                                     Data Architect
5633                               Senior Data Engineer
4888                       Data Lake Architect @ ONSITE
7913                              Sr. Software Engineer
3633                                Junior Data Analyst
4845                Snowflake/AWS Integration Architect
738                                 Migration Architect
1269                           Azure Migration Engineer
3597  Hiring for Back end engineers/C# .NET stack ||...

In [48]:
top_jobs[top_jobs['cluster']==26]['title']

235                             Senior Power BI Developer
187             Informatica Cloud Migration Lead-24-00289
7492                                  Lead Data Scientist
5583                          Data Scientist - Databricks
1509                            Data Engineer - Full Time
7771                       Generative AI - Data Scientist
252                         Sr. Azure Databricks Engineer
656                                        Technical Lead
1707                                       Data Architect
940                             Data Engineer 3: 24-00989
9801                          Azure Synapse Data Engineer
6774             MS Power Apps/Dynamics Software Engineer
5728                            Data Science Intern DIN48
4254                       Junior Data Analytics Engineer
3126                           Software Engineer II, Data
1590                             Program Analyst Power BI
5422                                         Data Analyst
1891                                        Data Engineer
8898                        Datawarehouse / ETL Developer
7944             Senior Data Modeler  (14+ years minimum)
2843                              IT Director - Pre Trade
4146                                        Data Engineer
8563                                      Data Engineer I
4668                         Databricks Platform Engineer
5589                            Databricks Data Architect
3862                Senior Data Analyst - Cloud Solutions
9909                    Software Engineer, Data Streaming
2789                            Data Management Developer
103          Sales Executive - Manufacturing Intelligence
343                                    Lead Data Engineer
328                                          Data Analyst
4073                                        Data Engineer
4458                IT Director - Transformation Programs
4491    Head of Corporate Technology Intelligent Syste...
3620                        Cloud Data Architect- ONLY W2
7400                                         Data Modeler
7393                      Solutions Architect(Databricks)
2703    Exciting Opportunity: Project Manager - Data M...
9707                                Business Data Analyst
5579                             Power Platform Architect
6731                             Data Operations Engineer
8185                                        Data Engineer
Name: title, dtype: object

In [49]:
career_domains = [
    "Data Engineering",
    "Data Science",
    "Business Intelligence",
    "Data Analytics"
]

for i, domain in enumerate(career_domains, start=1):
    print(f"{i}. {domain}")

1. Data Engineering
2. Data Science
3. Business Intelligence
4. Data Analytics