In [2]:
import pandas as pd
import numpy as np
import pickle

from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
import pandas as pd

jobs = pd.read_csv("../models/clean_jobs.csv")

jobs.head()

,title,description,company_name,location,formatted_experience_level,formatted_work_type,work_type,description_length
0,Marketing Coordinator,Job descriptionA leading real estate firm in N...,Corcoran Sawyer Smith,"Princeton, NJ",Not Specified,Full-time,FULL_TIME,2526
1,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",Unknown Company,"Fort Collins, CO",Not Specified,Full-time,FULL_TIME,3560
2,Assitant Restaurant Manager,The National Exemplar is accepting application...,The National Exemplar,"Cincinnati, OH",Not Specified,Full-time,FULL_TIME,462
3,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,"Abrams Fensterman, LLP","New Hyde Park, NY",Not Specified,Full-time,FULL_TIME,1599
4,Service Technician,Looking for HVAC service tech with experience ...,Unknown Company,"Burlington, IA",Not Specified,Full-time,FULL_TIME,232

In [4]:
jobs.shape

(119083, 8)

In [5]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119083 entries, 0 to 119082
Data columns (total 8 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   title                       119083 non-null  object
 1   description                 119083 non-null  object
 2   company_name                119083 non-null  object
 3   location                    119083 non-null  object
 4   formatted_experience_level  119083 non-null  object
 5   formatted_work_type         119083 non-null  object
 6   work_type                   119083 non-null  object
 7   description_length          119083 non-null  int64
dtypes: int64(1), object(7)
memory usage: 7.3+ MB

In [6]:
jobs.isnull().sum()

title                         0
description                   0
company_name                  0
location                      0
formatted_experience_level    0
formatted_work_type           0
work_type                     0
description_length            0
dtype: int64

In [7]:
jobs.columns

Index(['title', 'description', 'company_name', 'location',
       'formatted_experience_level', 'formatted_work_type', 'work_type',
       'description_length'],
      dtype='object')

In [8]:
jobs = jobs[
    [
        "title",
        "description"
    ]
]

jobs.head()

,title,description
0,Marketing Coordinator,Job descriptionA leading real estate firm in N...
1,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ..."
2,Assitant Restaurant Manager,The National Exemplar is accepting application...
3,Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...
4,Service Technician,Looking for HVAC service tech with experience ...

In [9]:
jobs["text"] = (
    jobs["title"].fillna("") + " " +
    jobs["description"].fillna("")
)

In [10]:
jobs["combined_text"] = (
    jobs["title"].fillna("").astype(str) + " " +
    jobs["description"].fillna("").astype(str)
)

In [14]:


vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(2, 3),
    min_df=5,
    max_df=0.5
)

X = vectorizer.fit_transform(jobs["combined_text"])

In [16]:
terms = vectorizer.get_feature_names_out()

print(len(terms))

2109632

In [17]:
import numpy as np

scores = np.asarray(
    X.sum(axis=0)
).flatten()

In [18]:
candidate_terms = pd.DataFrame({
    "term": terms,
    "score": scores
})

candidate_terms.head()

        term      score
0      00 00  48.266257
1   00 00 00   2.208275
2  00 00 000   1.234807
3   00 00 07   1.673711
4   00 00 10   0.464526

In [19]:
candidate_terms = candidate_terms.sort_values(
    by="score",
    ascending=False
)

candidate_terms.head(100)

                         term       score
469310       customer service  591.335855
2103805      years experience  555.494216
676695      equal opportunity  509.911710
1288152  opportunity employer  451.374225
1750437    sexual orientation  449.473917
...                       ...         ...
896580        human resources  196.809582
2097965        written verbal  195.932484
1479508     products services  195.661841
1780720          social media  193.356294
1027373      knowledge skills  192.439244

[100 rows x 2 columns]